### ISSUE TITLE
adapter.go:172:29: undefined: stm

### ISSUE THREAD

**Issue by wzbooks** [going/casbin-postgres-adaptor#5]
Hello, I made a mistake in executing this order:

`go get github.com/going/casbin-postgres-adapter`

`E:\GoWorks\src\github.com\going\casbin-postgres-adapter\adapter.go:172:29: undefined: stm`

**Comment by hsluoyz** [comment]
@wzbooks this code has bug. Before the owner fixes it, please use the Xorm Adapter (which also supports PostgreSQL) instead: https://github.com/casbin/xorm-adapter

**Comment by wzbooks** [comment]
@hsluoyz that's fine, thank you

**Comment by hsluoyz** [comment]
@wzbooks please close the issue if it's resolved :)

**Comment by hsluoyz** [comment]
@xiocode can you help solve this bug?
